repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: v1.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.1
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: mixed-line-ending
    args: ["--fix=lf"]
  - id: debug-statements
  - id: flake8
    additional_dependencies: [flake8-bugbear]
